#!/usr/bin/env bash
#MISE description="Run Swift tests with filtered output"

set -euo pipefail

export CLANG_MODULE_CACHE_PATH=".clang-module-cache"

swift test -j 8 --parallel --num-workers 8 -Xswiftc -suppress-warnings 2>&1 | bash .mise/helpers/swift-test-filter.sh
